# General config for all Distributions
rules:
  lowestEfficiency: 0.95
  highestWastedBytes: 0.2
  highestUserWastedPercent: 0.3

# Specific config by Distribution
# python:
#   rules:
#     lowestEfficiency: 0.90  # Distribution with more dependencies, more permissive threshold
#     highestWastedBytes: 0.25
#
# rhel:
#   rules:
#     highestUserWastedPercent: 0.35  # Distribution with more temporary files
#
# ubuntu:
#   rules:
#     lowestEfficiency: 0.97  # Simple Distribution, stricter threshold
