name: Docker Images Validation

on:
  push:
    paths:
      - 'distribution/*/Dockerfile'
      - '.github/workflows/docker-validate.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@main
        with:
          files: distribution/*/Dockerfile

      - name: Set matrix
        id: set-matrix
        run: |
          DIRS=$(echo '["'$(echo ${{ steps.changed-files.outputs.all_changed_files }} | \
                sed 's/ /","/g')'"]' | sed 's/\/Dockerfile//g')
          echo "matrix=${DIRS}" >> $GITHUB_OUTPUT

  validate:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' && needs.detect-changes.outputs.matrix != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get distribution name
        id: distribution
        run: echo "name=$(basename ${{ matrix.distribution }})" >> $GITHUB_OUTPUT

      - name: Install Hadolint
        run: |
          wget -q https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
          sudo chmod +x /usr/local/bin/hadolint

      - name: Run Hadolint
        run: hadolint ${{ matrix.distribution }}/Dockerfile

      - name: Set image name
        run: |
          IMAGE_NAME="${{ github.repository }}-$(basename ${{ matrix.distribution }})"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          export $(cat .env | xargs) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for analysis
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ matrix.distribution }}/Dockerfile
          push: false
          load: true
          tags: $IMAGE_NAME:test
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHON_VERSION=$PYTHON_VERSION
            TERRAFORM_VERSION=$TERRAFORM_VERSION
            OC_VERSION=$OC_VERSION
            BUILD_DATE=$(TZ=Europe/Madrid date)
            VERSION="test"
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
            GITHUB_REPOSITORY=${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Dive analysis
        uses: MaxymVlasov/dive-action@main
        with:
          image: $IMAGE_NAME:test
          config-file: ${{ github.workspace }}/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dockle security check
        uses: goodwithtech/dockle-action@main
        with:
          image: $IMAGE_NAME:test
          format: 'list'
          exit-code: '1'
          exit-level: 'warn'

  summary:
    needs: validate
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check validation status
        run: |
          if [ "${{ needs.validate.result }}" = "success" ]; then
            echo "✅ All distribution validations passed successfully"
            exit 0
          else
            echo "❌ Some distribution validations failed"
            exit 1
          fi
