name: Docker Images Validation

on:
  push:
    branches: [ "develop" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      distributions: ${{ steps.set-distro.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get changed files in the distribution folder
      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45.0.4
        with:
          files_yaml: |
            distro:
              - distribution/*/Dockerfile
            configs:
              - .env
              - requirements.txt
              - ssh_config
              - entrypoint.sh
              - ansible.cfg

      # Set distributions as a matrix
      - name: Set distributions
        id: set-distro
        run: |
          if [ "${{ steps.changed-files-yaml.outputs.distro_any_changed }}" == "true" ]; then
            echo "matrix=$(echo '["'$(echo ${{ steps.changed-files-yaml.outputs.distro_all_changed_files }} | \
            sed 's/ /","/g')'"]' | sed 's/\/Dockerfile//g')" >> $GITHUB_OUTPUT
          elif [ "${{ steps.changed-files-yaml.outputs.configs_any_changed }}" == "true" ]; then
            for file in $(ls -d ${{ github.workspace }}/distribution/* 2> /dev/null); do
              DISTRIBUTIONS+="$file "
            done
            echo "matrix=$(echo '["'$(echo ${DISTRIBUTIONS[@]} | sed 's/ /","/g')'"]')" >> $GITHUB_OUTPUT
          fi

  validate:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.distributions != '[""]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ${{ fromJson(needs.detect-changes.outputs.distributions) }}
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get distribution name from the matrix and set it as an environment variable
      - name: Get distribution name
        id: distribution
        run: echo "name=$(basename ${{ matrix.distro }})" >> $GITHUB_OUTPUT

      # Install Hadolint
      - name: Install Hadolint
        run: |
          wget -q https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
          sudo chmod +x /usr/local/bin/hadolint

      - name: Run Hadolint
        run: hadolint ${{ matrix.distro }}/Dockerfile

  summary:
    needs: validate
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check validation status
        run: |
          if [ "${{ needs.validate.result }}" = "success" ]; then
            echo "✅ All distribution validations passed successfully"
            exit 0
          elif [ "${{ needs.validate.result }}" = "skipped" ]; then
            echo "⚠️ No distribution validations were run"
            exit 0
          else
            echo "❌ Some distribution validations failed"
            exit 1
          fi
